import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { LoginPage } from "./partials/login-page";
import { NextAuthProvider } from "@/providers/sessionProvider";
import { ReactNode } from "react";
import { getServerSession } from "next-auth";
import { authOptions } from "../api/auth/[...nextauth]/route";
import { redirect } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "GalgJur",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  const session = await getServerSession(authOptions);

  if (session) {
    redirect("/dashboard");
  }

  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <NextAuthProvider>
          <LoginPage>{children}</LoginPage>
        </NextAuthProvider>
      </body>
    </html>
  );
}
