import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { LoginPage } from "./partials/login-page";
import { NextAuthProvider } from "@/providers/sessionProvider";
import { ReactNode } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "GalgJur",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <NextAuthProvider>
          <LoginPage>{children}</LoginPage>
        </NextAuthProvider>
      </body>
    </html>
  );
}
