import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { ReactNode } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "404 Not found",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body className={`flex h-screen flex-col ${inter.className}`}>
        <main className="flex flex-grow items-center justify-center">
          {children}
        </main>
      </body>
    </html>
  );
}
