import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Nav from "./partials/nav";
import { NextAuthProvider } from "@/providers/sessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body className={`flex h-screen flex-col ${inter.className}`}>
        <NextAuthProvider>
          <Nav />
          <main className="flex flex-grow items-center justify-center">
            {children}
          </main>
        </NextAuthProvider>
      </body>
    </html>
  );
}
